server:
  port: 6090


//configuration Your database details
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employeesmanagment
    username: 
    password:

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
